version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/BlogDb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: BlogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
